version: '3.7'
services:
  microservice1:
    build:
      context: ./backend/microservice1
    container_name: microservice1
    expose:
      - 3001
    networks:
      - nodejs-demo

  microservice2:
    build:
      context: ./backend/microservice2
    container_name: microservice2
    expose:
      - 3002
    networks:
      - nodejs-demo

  microservice3:
    build:
      context: ./backend/microservice3
    container_name: microservice3
    expose:
      - 3003
    networks:
      - nodejs-demo

  microservice4:
    build:
      context: ./backend/microservice4
    container_name: microservice4
    expose:
      - 3004
    networks:
      - nodejs-demo

  microservice5:
    build:
      context: ./backend/microservice5
    container_name: microservice5
    expose:
      - 3005
    networks:
      - nodejs-demo

  api-gw:
    build:
      context: ./backend/api-gw
    container_name: api-gw
    ports:
      - "3000:3000"
    depends_on:
      - microservice1
      - microservice2
      - microservice3
      - microservice4
      - microservice5
    networks:
      - nodejs-demo

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 8000:3000
    depends_on:
      - api-gw
    networks:
      - nodejs-demo

networks:
  nodejs-demo:
    driver: bridge
    name: nodejs-demo
    external: true